# Generated by Django 6.0.2 on 2026-02-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "link",
                    models.URLField(
                        help_text="Ссылка на сайт или инстаграм или что-то еще",
                        max_length=255,
                        verbose_name="Ссылка",
                    ),
                ),
                ("logo", models.ImageField(upload_to="partners/", verbose_name="Логотип")),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
        ),
    ]
