# Generated by Django 6.0.2 on 2026-02-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_attribute_name_alter_brand_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'Название', 'verbose_name_plural': 'Название'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'values', 'verbose_name_plural': 'values'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Лого бренда', 'verbose_name_plural': 'Название бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Описание', 'verbose_name_plural': 'Описание'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Артикул', 'verbose_name_plural': 'Артикул'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отхывы', 'verbose_name_plural': 'отзывы'},
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='attribute',
            new_name='attributes',
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=1, verbose_name='НАзвание товара на складе'),
        ),
    ]
