# Generated by Django 6.0.2 on 2026-02-18 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'атрибут', 'verbose_name_plural': 'Атрибут'},
        ),
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'значение атрибута', 'verbose_name_plural': 'Значение атрибута'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'бренды', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'продукт', 'verbose_name_plural': 'Продукт'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'фотки', 'verbose_name_plural': 'Фото'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'вариант продукта', 'verbose_name_plural': 'Вариант продукта'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'отзывы', 'verbose_name_plural': 'Oтзывы'},
        ),
    ]
