# Generated by Django 6.0.2 on 2026-02-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantity',
            new_name='quantitly',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='varant',
            new_name='variant',
        ),
    ]
