# Generated by Django 6.0.2 on 2026-02-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='РџРѕРґР·Р°РіРѕР»РѕРІРѕРє')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='РћРїРёСЃР°РЅРёРµ')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='РўРµРєСЃС‚ РєРЅРѕРїРєРё')),
                ('button_link', models.URLField(blank=True, max_length=255, verbose_name='РЎСЃС‹Р»РєР° РєРЅРѕРїРєРё')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Р\x98Р·РѕР±СЂР°Р¶РµРЅРёРµ')),
                ('is_active', models.BooleanField(default=True, verbose_name='РђРєС‚РёРІРµРЅ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='РџРѕСЂСЏРґРѕРє')),
                ('text_align', models.CharField(choices=[('left', 'РЎР»РµРІР°'), ('center', 'РџРѕ С†РµРЅС‚СЂСѓ')], default='left', max_length=10, verbose_name='Р’С‹СЂР°РІРЅРёРІР°РЅРёРµ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'РЎР»Р°Р№Рґ',
                'verbose_name_plural': 'РЎР»Р°Р№РґС‹',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
