# Generated by Django 6.0.2 on 2026-04-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_img', models.ImageField(upload_to='about/', verbose_name='Большое изображение')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('autograph_img', models.ImageField(upload_to='about/', verbose_name='Авторская фотография')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='BlogAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блог',
            },
        ),
        migrations.CreateModel(
            name='Fag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вопросы/Ответы',
                'verbose_name_plural': 'вопросы/ответы',
            },
        ),
        migrations.CreateModel(
            name='PlusAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(upload_to='about/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Плюсы',
                'verbose_name_plural': 'Плюсы',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=150, verbose_name='Подзаголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('button_text', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('button_link', models.URLField(blank=True, max_length=255, verbose_name='Ссылка кнопки')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('text_align', models.CharField(choices=[('left', 'Слева'), ('center', 'По центру')], default='left', max_length=10, verbose_name='Выравнивание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='about/', verbose_name='Аватар')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'отзывы',
                'verbose_name_plural': 'отзывы ',
            },
        ),
    ]
