# Generated by Django 6.0.2 on 2026-02-27 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abuot', '0002_aboutcontent_blogabout_fag_plusabout_testimonials_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonials',
            options={'verbose_name': 'отзывы', 'verbose_name_plural': 'отзывы '},
        ),
    ]
